name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Pull latest code from GitHub
        uses: appleboy/ssh-action@master
        with:
          host: 65.1.96.64
          username: ubuntu
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/html
            sudo git fetch --all
            sudo git reset --hard origin/master
            sudo chown -R www-data:www-data /var/www/html
            echo "CI/CD Deployment successful!"
